### ISSUE TITLE
Converted SVGs Don't Appear to Display Text

### ISSUE THREAD

**Issue by jbenner-radham** [oslllo/svg2#40]
Hello,

First off, thanks for producing this library. It was the only one I could find that didn't rely on a headless browser and I really like the chained API style.

However, unfortunately it seems like it doesn't render text when converting SVGs. I'm using v3.0.0 of the library and I've tried converting to PNG and JPEG formats.

Here's an example SVG that lets me reproduce the issue:

```svg
<svg viewBox="0 0 1920 1080" xmlns="http://www.w3.org/2000/svg">
  <rect class="background" width="100%" height="100%" fill="#f0db4f" />
  <text
    x="50%"
    y="50%"
    fill="#323330"
    font-family="sans-serif"
    font-weight="bold"
    font-size="300px"
    dominant-baseline="middle"
    text-anchor="middle"
  >
    Hello world!
  </text>
</svg>
```

And here's an example script of what I'm using to convert the SVGs:

```js
import Svg2 from 'oslllo-svg2';

try {
    await Svg2('image.svg').png().toFile('image.png');
    console.log('Converted image to PNG.');
} catch (error) {
    console.error(error);
}
```

I don't get any errors when running that script and it produces the PNG file, the text is just missing. And I can open the SVGs in Inkscape, Firefox, etc. and they look fine there.

**Comment by Ghustavh97** [comment]
Try `v4.0.0`

**Comment by jbenner-radham** [comment]
@Ghustavh97 it works brilliantly now! Thanks a bunch!
